mime_to_extensions = {
    "audio/aac": ["aac"],
    "audio/aac": ["adts"],
    "audio/aiff": ["aiff"],
    "audio/x-flac": ["flac"],
    "video/mp4": ["mov, mp4, m4a, 3gp, 3g2, mj2"],
    "audio/mpeg": ["mp2"],
    "audio/mpeg": ["mp3"],
    "audio/ogg": ["oga"],
    "application/ogg": ["ogg"],
    "audio/x-oma": ["oma"],
    "audio/ogg": ["opus"],
    "audio/ogg": ["spx"],
    "audio/x-wav": ["wav"],
    "audio/x-wavpack": ["wv"],
}

extensions_to_mime = {
    "aac": "audio/aac",
    "adts": "audio/aac",
    "aiff": "audio/aiff",
    "flac": "audio/x-flac",
    "mov": "video/mp4",
    "mp4": "video/mp4",
    "m4a": "video/mp4",
    "3gp": "video/mp4",
    "3g2": "video/mp4",
    "mj2": "video/mp4",
    "mp2": "audio/mpeg",
    "mp3": "audio/mpeg",
    "oga": "audio/ogg",
    "ogg": "application/ogg",
    "oma": "audio/x-oma",
    "opus": "audio/ogg",
    "spx": "audio/ogg",
    "wav": "audio/x-wav",
    "wv": "audio/x-wavpack",
}
