"""

Revision ID: e566fa3c804c
Revises: cf278f4d6e8f
Create Date: 2023-08-14 16:58:57.037153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e566fa3c804c'
down_revision = 'cf278f4d6e8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
